language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
    - pip install -r .travis-requirements.txt

script: make all

branches:
  only:
    - master

notifications:
  email: false
